package org.diagnoseit.spike.rules;

//list any import classes here.
import org.diagnoseit.spike.trace.Trace;
import org.diagnoseit.spike.trace.SubTrace;
import org.diagnoseit.spike.rules.impl.SlowMethodRule;
import org.diagnoseit.spike.rules.impl.ExcessiveRPCRule;
import org.diagnoseit.spike.tag.Tag;
import org.diagnoseit.spike.tag.SlowMethodTag;

//declare any global variables here

rule "Find callable contributing most to the response time"
	when
		trace:Trace(root != null &&  root.root != null);
	then
		SlowMethodRule slowMethodRule = new SlowMethodRule();
		slowMethodRule.execute(trace);
		
		if (slowMethodRule.hasTag()) {
			insert(slowMethodRule.getSlowMethodTag());
		}
				
end

rule "Find identical callees"
    when
	    tag:SlowMethodTag();
    then
        ExcessiveRPCRule excessiveRPCRule = new ExcessiveRPCRule();
        excessiveRPCRule.execute(tag);
end

rule "Your Second Rule"
    //include attributes such as "salience" here...
    when
        //conditions
    then
        //actions

end