//created on: 21.07.2015.
package org.diagnoseit.spike.rules

//list any import classes here.
import org.diagnoseit.spike.trace.Trace;


//declare any global variables here




rule "Your First Rule"

    when
        //conditions
        // trace: Trace(root: rootTrace);
        trace: Trace(rootTrace.root.operationName != null) 
    then
        //actions
        System.out.println("trace:" + trace);

end

rule "Your Second Rule"
    //include attributes such as "salience" here...
    when
        //conditions
    then
        //actions

end
